build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian
  amd64: ghcr.io/home-assistant/amd64-base-debian
  armhf: ghcr.io/home-assistant/armhf-base-debian
  armv7: ghcr.io/home-assistant/armv7-base-debian
  i386: ghcr.io/home-assistant/i386-base-debian