name: "Firefly III"
description: "An unofficial add-on for a self-hosted manager for your personal finances."
url: https://docs.firefly-iii.org
version: "6.1.16-7"
slug: "fireflyiii"
arch: [aarch64, amd64]
init: false
ingress: true
panel_icon: mdi:account-cash-outline
panel_title: Firefly III
panel_admin: true
ports:
  80/tcp: 3473
map:
  - config:rw
environment:
  DB_CONNECTION: sqlite
  DB_DATABASE: /config/addons_config/fireflyiii/database/database.sqlite
options:
  APP_KEY: null
schema:
  APP_KEY: str
